const weatherData = [
    {
        id: 1,
        city: "New York",
        temperature: 72,
        condition: "Sunny",
        risetime: "05:20",
        settime:"18:20",
        humidity:50,
        wind:40,
        precipitation:8,
        uv:35,
        feels:44,
        chances:70,
    },
    {
        id: 2,
        city: "Los Angeles",
        temperature: 85,
        condition: "Clear",
        risetime: "5:30",
        settime:"18:30",
        humidity:40,
        wind:20,
        precipitation:3,
        uv:56,
        feels:78,
        chances:20,
    },
    {
        id: 3,
        city: "Chicago",
        temperature: 68,
        condition: "Partly Cloudy",
        risetime: "5:40",
        settime:"18:40",
        humidity:60,
        wind:70,
        precipitation:5,
        uv:34,
        feels:57,
        chances:90,
    },
    {
        id: 4,
        city: "Houston",
        temperature: 90,
        condition: "Mostly Sunny",
        risetime: "5:50",
        settime:"18:50",
        humidity:20,
        wind:30,
        precipitation:6,
        uv:65,
        feels:45,
        chances:79,
    },
    {
        id: 5,
        city: "Miami",
        temperature: 80,
        condition: "Cloudy",
        risetime: "6:00",
        settime:"19:00",
        humidity:70,
        wind:80,
        precipitation:8,
        uv:10,
        feels:58,
        chances:30,
    },
];

export default weatherData;
